server:
  port: 9001
  shutdown: graceful

logging:
  level:
    org.springframework: info

management:
  endpoints:
    web:
      exposure:
        include: ["prometheus", "health"]

springdoc:
  api-docs:
    path: /api-docs

spring:
  application:
    name: catalog-service
  threads:
    virtual:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: false
    open-in-view: false
  r2dbc:
    url: r2dbc:postgresql://localhost:15432/catalog
    password: postgres
    username: postgres
    pool:
      enabled: true
      max-acquire-time: 20s
      initial-size: 10
      max-idle-time: 30s
      max-size: 20
      max-create-connection-time: 30s
  liquibase:
    user: postgres
    driver-class-name: org.postgresql.Driver
    change-log: classpath:db/changelog/changelog-master.yaml
    password: postgres
    url: jdbc:postgresql://localhost:15432/catalog
    enabled: true
  main:
    allow-bean-definition-overriding: true