server:
  port: 9003
  shutdown: graceful

logging:
  level:
    org.springframework: info

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    enabled: false
    sampling:
      probability: 1.0

spring:
  application:
    name: shop-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: false
      routes:
        - id: catalog-service
          uri: http://localhost:9001
          predicates:
            - Path=/catalog/**
          filters:
            - RewritePath=/catalog/?(?<segment>.*), /${segment}
        - id: orders-service
          uri: http://localhost:9002
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order/?(?<segment>.*), /${segment}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/?(?<segment>.*), /${segment}/v3/api-docs
        - id: swagger-ui
          uri: http://localhost:${server.port}
          predicates:
            - Path=/swagger-ui/**
          filters:
            - RewritePath=/swagger-ui/?(?<segment>.*), /swagger-ui/${segment}
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers RETAIN_FIRST
  mvc:
    problemdetails:
      enabled: true

springdoc:
  swagger-ui:
    use-root-path: true
    urls:
      - name: catalog
        url: /v3/api-docs/catalog
      - name: orders
        url: /v3/api-docs/order
    enabled: true