logging:
  level:
    org.springframework: info

management:
  endpoints:
    web:
      exposure:
        include: ["prometheus", "health"]

spring:
  application:
    name: order-service
  threads:
    virtual:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: false
    open-in-view: false
  r2dbc:
    url: r2dbc:postgresql://localhost:25432/orders
    password: postgres
    username: postgres
    pool:
      enabled: true
      max-acquire-time: 20s
      initial-size: 10
      max-idle-time: 30s
      max-size: 20
      max-create-connection-time: 30s
  liquibase:
    user: postgres
    driver-class-name: org.postgresql.Driver
    change-log: classpath:/db/migration/changelog-master.yaml
    password: postgres
    url: jdbc:postgresql://localhost:25432/orders
    enabled: true
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 9002
  shutdown: graceful
orders:
  catalog-service-url: http://localhost:8081
  order-events-exchange: orders-exchange
  new-orders-queue: new-orders
  delivered-orders-queue: delivered-orders
  cancelled-orders-queue: cancelled-orders
  error-orders-queue: error-orders